glog:
  minLogLevel: 0
  logName: glog_main
  logToStderr: true
  customLogFormat: true
grpc:
  serverAddress: "localhost:50051"
  keepalivePermitWithoutCalls: 1
  keepaliveTimeMs: 30000
  keepaliveTimeoutMs: 5000